### ISSUE TITLE
Yasnippet cannot find the snippets

### ISSUE THREAD

**Issue by awbertulli** [sei40kr/license-snippets#2]
Hi! I installed the package and put the initialization elisp code as reported in the README. However, it isn't clear to me by what keywords should I call the snippet expansion. If I search in the yasnippet menu I can't find them. Where should I look? Fundamental mode? Prog?
Thanks in advance

**Comment by sei40kr** [comment]
@bertulli 
I'm going to list all snippet keywords in README when I have time.

Until then, please see here for the keywords.
https://github.com/sei40kr/license-snippets/tree/master/snippets/text-mode

Please be noted that the license snippets can be found only in `LICENSE` file.

**Comment by awbertulli** [comment]
Got it, thanks. :smile:
